/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentAreaRouteImport } from './routes/student-area'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CbseRouteImport } from './routes/cbse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StudentAreaRoute = StudentAreaRouteImport.update({
  id: '/student-area',
  path: '/student-area',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CbseRoute = CbseRouteImport.update({
  id: '/cbse',
  path: '/cbse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cbse': typeof CbseRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-area': typeof StudentAreaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cbse': typeof CbseRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-area': typeof StudentAreaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cbse': typeof CbseRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/student-area': typeof StudentAreaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cbse'
    | '/contact'
    | '/facilities'
    | '/sitemap.xml'
    | '/student-area'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cbse'
    | '/contact'
    | '/facilities'
    | '/sitemap.xml'
    | '/student-area'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cbse'
    | '/contact'
    | '/facilities'
    | '/sitemap.xml'
    | '/student-area'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CbseRoute: typeof CbseRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudentAreaRoute: typeof StudentAreaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student-area': {
      id: '/student-area'
      path: '/student-area'
      fullPath: '/student-area'
      preLoaderRoute: typeof StudentAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cbse': {
      id: '/cbse'
      path: '/cbse'
      fullPath: '/cbse'
      preLoaderRoute: typeof CbseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CbseRoute: CbseRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudentAreaRoute: StudentAreaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
